import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "deep-navy": {
          "50": "#eaedfb",
          "100": "#d4dbf7",
          "200": "#aab7ee",
          "300": "#7f94e6",
          "400": "#5570dd",
          "500": "#2a4cd5",
          "600": "#223daa",
          "700": "#192e80",
          "800": "#111e55",
          "900": "#080f2b",
          "950": "#060b1e",
        },
        "ocean-twilight": {
          "50": "#e9eefb",
          "100": "#d3ddf8",
          "200": "#a7bbf1",
          "300": "#7b99ea",
          "400": "#5077e2",
          "500": "#2455db",
          "600": "#1d44af",
          "700": "#153384",
          "800": "#0e2258",
          "900": "#07112c",
          "950": "#050c1f",
        },
        "ocean-blue": {
          "50": "#ebf5fa",
          "100": "#d7ebf4",
          "200": "#afd8e9",
          "300": "#87c4de",
          "400": "#5fb0d3",
          "500": "#379dc8",
          "600": "#2c7da0",
          "700": "#215e78",
          "800": "#163f50",
          "900": "#0b1f28",
          "950": "#08161c",
        },
        "bright-sky": {
          "50": "#e9f6fb",
          "100": "#d4edf7",
          "200": "#a8daf0",
          "300": "#7dc8e8",
          "400": "#52b6e0",
          "500": "#26a3d9",
          "600": "#1f83ad",
          "700": "#176282",
          "800": "#0f4157",
          "900": "#08212b",
          "950": "#05171e",
        },
        "alice-blue": {
          "50": "#ebf2fa",
          "100": "#d7e4f4",
          "200": "#aec9ea",
          "300": "#86aedf",
          "400": "#5e93d4",
          "500": "#3678c9",
          "600": "#2b60a1",
          "700": "#204879",
          "800": "#153051",
          "900": "#0b1828",
          "950": "#07111c",
        },
        "space-indigo": {
          "50": "#eff0f6",
          "100": "#dee0ed",
          "200": "#bec2da",
          "300": "#9da3c8",
          "400": "#7c84b6",
          "500": "#5c65a3",
          "600": "#495183",
          "700": "#373d62",
          "800": "#252941",
          "900": "#121421",
          "950": "#0d0e17",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      boxShadow: {
        "2xs": "var(--shadow-2xs)",
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
        ],
        serif: [
          "Lora",
          "ui-serif",
          "Georgia",
          "Cambria",
          "Times New Roman",
          "Times",
          "serif",
        ],
        mono: [
          "Space Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
